export default {
  columns: [
    { name: 'button', title: ' ' },
    { name: 'avatar', title: 'Аватар' },
    { name: 'full_name', title: 'ФИО сотрудника' },
    { name: 'registration_date', title: 'Дата регистрации' },
    { name: 'phone', title: 'Телефон' },
    { name: 'email', title: 'Электронная почта' },
    { name: 'date_of_birth', title: 'Дата рождения' },
    { name: 'age', title: 'Возраст' },
    { name: 'sex', title: 'Пол' },
  ],
  defaultOrder: [
    'button',
    'avatar',
    'full_name',
    'registration_date',
    'phone',
    'email',
    'date_of_birth',
    'age',
    'sex',
  ],
  defaultColumnWidths: [
    { columnName: 'button', width: 100 },
    { columnName: 'avatar', width: 100 },
    { columnName: 'full_name', width: 300 },
    { columnName: 'registration_date', width: 250 },
    { columnName: 'phone', width: 200 },
    { columnName: 'email', width: 300 },
    { columnName: 'date_of_birth', width: 200 },
    { columnName: 'age', width: 150 },
    { columnName: 'sex', width: 200 },
  ],
  sortingStateColumnExtensions: [
    { columnName: 'avatar', sortingEnabled: false },
    { columnName: 'button', sortingEnabled: false },
  ],
  textFilterOperations: ['contains', 'startsWith', 'endsWith', 'equal'],
  numberFilterOperations: [
    'greaterThan',
    'greaterThanOrEqual',
    'lessThan',
    'lessThanOrEqual',
    'equal',
  ],
  sexFilterOperations: ['equal'],
  dateFilterOperations: [
    'greaterThan',
    'greaterThanOrEqual',
    'lessThan',
    'lessThanOrEqual',
    'equal',
  ],
  dateTimeFilterOperations: ['greaterThan', 'greaterThanOrEqual', 'lessThan', 'lessThanOrEqual'],
  textColumns: ['full_name', 'phone', 'email'],
  numberColumns: ['age'],
  dateColumns: ['date_of_birth'],
  dateTimeColumns: ['registration_date'],
  avatarColumns: ['avatar'],
  buttonColumns: ['button'],
  sexColumns: ['sex'],
};
